# Generated by Django 5.0.1 on 2025-11-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=300)),
                ("category", models.CharField(max_length=100)),
                ("french_summary", models.TextField()),
                ("english_summary", models.TextField()),
                ("mood", models.CharField(max_length=100)),
                ("source_urls", models.JSONField(blank=True, default=list)),
                ("source_names", models.JSONField(blank=True, default=list)),
                ("thumbnails", models.JSONField(blank=True, default=list)),
                (
                    "french_audio",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "english_audio",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("timestamp", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("reaction_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commenter_name", models.CharField(max_length=50)),
                ("comment_text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="api.article",
                    ),
                ),
            ],
        ),
    ]
