# Generated by Django 5.2.8 on 2025-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_visitorsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="mood",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="article",
            name="view_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
