# Generated by Django 5.2.8 on 2025-11-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_article_category_alter_article_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="headline_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="headline_fr",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="headline",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
