# Generated by Django 5.2.8 on 2025-11-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_article_headline_en_article_headline_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail_image",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
        migrations.AlterField(
            model_name="article",
            name="english_audio",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="audio/english/"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="french_audio",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="audio/french/"
            ),
        ),
    ]
