# Generated by Django 5.2.8 on 2025-11-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_article_thumbnail_image_alter_article_english_audio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FCMSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=500, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="send_notification",
            field=models.BooleanField(default=False),
        ),
    ]
