# Generated by Django 5.2.8 on 2025-11-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_fcmsubscription_article_send_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcmsubscription",
            name="preferred_language",
            field=models.CharField(
                choices=[("fr", "French"), ("en", "English")],
                default="fr",
                help_text="User's preferred language for notifications",
                max_length=2,
            ),
        ),
    ]
