# Generated by Django 5.2.8 on 2025-11-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_fcmsubscription_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmsubscription",
            name="preferred_language",
            field=models.CharField(
                choices=[("fr", "French"), ("en", "English")],
                db_index=True,
                default="fr",
                help_text="User's preferred language for notifications",
                max_length=2,
            ),
        ),
    ]
