# Generated by Django 5.2.8 on 2025-12-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_add_language_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcmsubscription",
            name="category_preferences",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of preferred category IDs for targeted notifications",
            ),
        ),
    ]
