# Generated by Django 5.2.8 on 2025-12-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_add_category_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcmsubscription",
            name="last_notification_date",
            field=models.DateField(
                blank=True,
                help_text="Date of last notification sent (for daily limit reset)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fcmsubscription",
            name="notifications_sent_today",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of random notifications sent today (for users without preferences)",
            ),
        ),
    ]
