# Generated by Django 5.2.8 on 2025-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_add_notification_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcmsubscription",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Email for linking to Pro subscription (optional)",
                max_length=254,
                null=True,
            ),
        ),
    ]
