# Generated by Django 5.2.8 on 2025-12-20 12:51

import django.db.models.deletion
from django.db import migrations, models


def copy_category_to_legacy(apps, schema_editor):
    """Copy existing category string values to category_legacy before altering the field"""
    Article = apps.get_model('api', 'Article')
    # We need to use raw SQL since the model is in transition
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE api_article SET category_legacy = category WHERE category IS NOT NULL"
        )


def reverse_copy(apps, schema_editor):
    """Reverse: copy from legacy back to category"""
    pass  # Will be handled by normal migration revert


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_fcmsubscription_email"),
    ]

    operations = [
        # Step 1: Create the ArticleCategory model
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(help_text="English name", max_length=100)),
                ("name_fr", models.CharField(help_text="French name", max_length=100)),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                (
                    "main_category",
                    models.CharField(
                        choices=[
                            ("ACTUALITY", "Actuality"),
                            ("OPPORTUNITY", "Opportunity"),
                            ("FOR_YOU", "For You"),
                        ],
                        db_index=True,
                        help_text="Parent category (Actuality, Opportunity, or For You)",
                        max_length=20,
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True, help_text="Optional emoji icon", max_length=10
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within main category"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Article Category",
                "verbose_name_plural": "Article Categories",
                "ordering": ["main_category", "order", "name_en"],
            },
        ),
        # Step 2: Add the legacy field first
        migrations.AddField(
            model_name="article",
            name="category_legacy",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        # Step 3: Copy existing category values to legacy field
        migrations.RunPython(copy_category_to_legacy, reverse_copy),
        # Step 4: Remove the old category field
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        # Step 5: Add the new category ForeignKey field
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="api.articlecategory",
            ),
        ),
    ]
