# Generated by Django 5.2.8 on 2025-12-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_add_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="deadline",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Application/submission deadline (for scholarships, jobs, concours)",
                null=True,
            ),
        ),
    ]
