# Generated by Django 5.2.8 on 2025-12-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_add_deadline_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, help_text="User's name (optional)", max_length=100
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True,
                        help_text="User's email for follow-up",
                        max_length=254,
                    ),
                ),
                (
                    "user_phone",
                    models.CharField(
                        blank=True,
                        help_text="User's WhatsApp/phone number",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="User's description of what help they need"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal notes for team"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        help_text="The article the user needs help with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistance_requests",
                        to="api.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistance Request",
                "verbose_name_plural": "Assistance Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
