# Generated by Django 5.2.8 on 2025-12-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_add_assistance_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_name",
                    models.CharField(
                        default="Reepls AI",
                        help_text="Name the AI uses to identify itself",
                        max_length=50,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are Reepls AI, a helpful assistant for Gist4U - a platform that helps users discover opportunities in Cameroon (scholarships, jobs, concours, news).\n\nYour role is to help users understand articles and answer questions about opportunities.\n\nGuidelines:\n- Always be concise (max 500 characters)\n- Be friendly but professional\n- Answer in the same language the user writes in\n- If you don't know something, say so\n- Focus on being helpful about the specific article context provided",
                        help_text="System instructions sent to Gemini API",
                    ),
                ),
                (
                    "max_response_length",
                    models.PositiveIntegerField(
                        default=500, help_text="Maximum characters for AI responses"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable AI chat feature"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Settings",
                "verbose_name_plural": "AI Settings",
            },
        ),
    ]
