# Generated by Django 5.2.8 on 2025-12-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_add_ai_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisettings",
            name="system_prompt",
            field=models.TextField(
                default="You are Reepls AI, a helpful assistant for Gist4U - a platform that helps users discover opportunities in Cameroon (scholarships, jobs, concours, news).\n\nYour role is to help users understand articles and answer questions about opportunities.\n\nGuidelines:\n- Be concise (max 500 characters per response)\n- Be friendly but professional\n- Answer in the same language the user writes in\n- If you don't know something, say so honestly\n- On your FIRST response, you may reference the article context\n- On follow-up responses, answer naturally without repeatedly saying \"this article\" - just respond directly to the user's question\n- Have a natural conversation flow, like a helpful friend who read the article",
                help_text="System instructions sent to Gemini API",
            ),
        ),
        migrations.CreateModel(
            name="DailyQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("CHRISTIAN", "Christian"),
                            ("ISLAMIC", "Islamic"),
                        ],
                        db_index=True,
                        help_text="Quote category matching user preferences",
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="The date this quote is for"
                    ),
                ),
                ("quote_text", models.TextField(help_text="The quote itself")),
                (
                    "author",
                    models.CharField(
                        help_text="Author or source of the quote", max_length=150
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Explanation of the quote's meaning and context"
                    ),
                ),
                (
                    "affirmations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of affirmation strings related to the quote",
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Bible verse, Hadith reference, book title, etc.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Quote",
                "verbose_name_plural": "Daily Quotes",
                "ordering": ["-date", "category"],
                "unique_together": {("category", "date")},
            },
        ),
    ]
