# Generated by Django 5.2.8 on 2025-12-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_aisettings_system_prompt_dailyquote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyquote",
            name="affirmations",
        ),
        migrations.RemoveField(
            model_name="dailyquote",
            name="explanation",
        ),
        migrations.RemoveField(
            model_name="dailyquote",
            name="quote_text",
        ),
        migrations.AddField(
            model_name="dailyquote",
            name="affirmations_en",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of affirmation strings in English",
            ),
        ),
        migrations.AddField(
            model_name="dailyquote",
            name="affirmations_fr",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of affirmation strings in French",
            ),
        ),
        migrations.AddField(
            model_name="dailyquote",
            name="explanation_en",
            field=models.TextField(default="", help_text="Explanation in English"),
        ),
        migrations.AddField(
            model_name="dailyquote",
            name="explanation_fr",
            field=models.TextField(default="", help_text="Explanation in French"),
        ),
        migrations.AddField(
            model_name="dailyquote",
            name="quote_text_en",
            field=models.TextField(default="", help_text="The quote in English"),
        ),
        migrations.AddField(
            model_name="dailyquote",
            name="quote_text_fr",
            field=models.TextField(default="", help_text="The quote in French"),
        ),
    ]
