# Generated by Django 5.2.8 on 2025-12-20 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_remove_dailyquote_affirmations_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Notification title in English", max_length=200
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True,
                        help_text="Notification title in French",
                        max_length=200,
                    ),
                ),
                (
                    "message_en",
                    models.TextField(help_text="Notification message in English"),
                ),
                (
                    "message_fr",
                    models.TextField(
                        blank=True, help_text="Notification message in French"
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="Image URL for notification",
                        max_length=500,
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="Custom URL if no article linked",
                        max_length=500,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("FOR_YOU", "For You (Personalized)"),
                            ("ARTICLE", "New Article"),
                            ("SYSTEM", "System Notification"),
                            ("PROMO", "Promotional"),
                            ("REMINDER", "Reminder"),
                        ],
                        db_index=True,
                        default="ARTICLE",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related article (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="api.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification",
                "verbose_name_plural": "User Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="api_usernot_user_id_9a28fe_idx",
                    )
                ],
            },
        ),
    ]
