# Generated by Django 5.2.8 on 2025-12-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_usernotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="english_audio",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="french_audio",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
