# Generated by Django 5.2.8 on 2025-11-27 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(help_text="Cameroon phone number", max_length=20),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "subscribed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pro Subscription",
                "verbose_name_plural": "Pro Subscriptions",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
