# Generated by Django 5.2.8 on 2025-11-27 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                (
                    "phone",
                    models.CharField(
                        help_text="Organization contact number", max_length=20
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contacted",
                    models.BooleanField(
                        default=False, help_text="Has our agent contacted them?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement Inquiry",
                "verbose_name_plural": "Advertisement Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
