# Generated by Django 5.2.8 on 2025-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_waitinglist"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="gist_preferences",
            field=models.CharField(
                default="scholarships, concours and jobs",
                help_text="What type of gist would you like to receive?",
                max_length=100,
            ),
        ),
    ]
