# Generated by Django 5.2.8 on 2025-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_subscription_gist_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="notified_of_expiry",
            field=models.BooleanField(
                default=False,
                help_text="Has the user been notified their subscription expired?",
            ),
        ),
    ]
