# Generated by Django 5.2.8 on 2025-12-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_subscription_notified_of_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique coupon code (e.g., GIST20)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "discount_percent",
                    models.IntegerField(help_text="Discount percentage (1-100)"),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum number of times this coupon can be used",
                    ),
                ),
                (
                    "current_uses",
                    models.IntegerField(
                        default=0, help_text="How many times this coupon has been used"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of user who used the coupon", max_length=254
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="web.coupon",
                    ),
                ),
            ],
            options={
                "ordering": ["-used_at"],
                "unique_together": {("coupon", "email")},
            },
        ),
    ]
