# Generated by Django 5.2.8 on 2025-12-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_coupon_couponusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trans_id",
                    models.CharField(
                        help_text="Fapshi transaction ID", max_length=100, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("amount", models.IntegerField(help_text="Amount in FCFA")),
                (
                    "final_amount",
                    models.IntegerField(help_text="Amount after coupon discount"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PENDING", "Pending"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "gist_preferences",
                    models.CharField(
                        default="scholarships, concours and jobs", max_length=100
                    ),
                ),
                ("is_renewal", models.BooleanField(default=False)),
                (
                    "medium",
                    models.CharField(
                        blank=True,
                        help_text="mobile money or orange money",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "financial_trans_id",
                    models.CharField(
                        blank=True,
                        help_text="Operator transaction ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.coupon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
