# Generated by Django 5.2.8 on 2025-12-15 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_paymenttransaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WaitingList",
        ),
    ]
