# Generated by Django 5.2.8 on 2025-12-15 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_delete_waitinglist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Cameroon phone number (6XXXXXXXX)", max_length=20
                    ),
                ),
                (
                    "interests",
                    models.JSONField(
                        default=list, help_text="Selected interest categories"
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("FSLC", "FSLC (Primary)"),
                            ("GCE_OL", "GCE O/L"),
                            ("GCE_AL", "GCE A/L"),
                            ("HND", "HND"),
                            ("BACHELOR", "Bachelor's Degree"),
                            ("MASTERS", "Master's Degree"),
                            ("PHD", "PhD"),
                            ("RAS", "Prefer not to say"),
                        ],
                        default="RAS",
                        max_length=20,
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        choices=[
                            ("ARTS", "Arts & Humanities"),
                            ("SCIENCE", "Science & Technology"),
                            ("RAS", "Prefer not to say"),
                        ],
                        default="RAS",
                        max_length=20,
                    ),
                ),
                (
                    "notification_time",
                    models.TimeField(
                        default="08:00", help_text="Preferred notification time"
                    ),
                ),
                (
                    "custom_desires",
                    models.TextField(
                        blank=True, help_text="User's specific needs", null=True
                    ),
                ),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
