# Generated by Django 5.2.8 on 2025-12-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="region",
            field=models.CharField(
                choices=[
                    ("ADAMAWA", "Adamawa"),
                    ("CENTRE", "Centre"),
                    ("EAST", "East"),
                    ("FAR_NORTH", "Far North"),
                    ("LITTORAL", "Littoral"),
                    ("NORTH", "North"),
                    ("NORTHWEST", "Northwest"),
                    ("SOUTH", "South"),
                    ("SOUTHWEST", "Southwest"),
                    ("WEST", "West"),
                    ("RAS", "Prefer not to say"),
                ],
                default="RAS",
                help_text="Region of residence",
                max_length=20,
            ),
        ),
    ]
