# Generated by Django 5.2.8 on 2025-12-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_userprofile_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="quote_category",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General"),
                    ("CHRISTIAN", "Christian"),
                    ("ISLAMIC", "Islamic"),
                ],
                default="GENERAL",
                help_text="Quote category preference",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_quotes",
            field=models.BooleanField(default=True, help_text="Receive daily quotes"),
        ),
    ]
