# Generated by Django 5.2.8 on 2025-12-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_userprofile_quote_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorPartnerInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of contact person", max_length=100
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text="Company/Organization name (optional for individuals)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Website URL (optional)", null=True
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("SPONSOR", "Sponsor"),
                            ("PARTNER", "Partner"),
                            ("BOTH", "Both Sponsor & Partner"),
                        ],
                        default="SPONSOR",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of how they want to collaborate"
                    ),
                ),
                (
                    "contacted",
                    models.BooleanField(
                        default=False, help_text="Has our founder contacted them?"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this inquiry",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sponsor/Partner Inquiry",
                "verbose_name_plural": "Sponsor/Partner Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
