# Generated by Django 5.2.8 on 2025-12-17 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_sponsorpartnerinquiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("profession", models.CharField(max_length=150)),
                ("location", models.CharField(max_length=100)),
                ("bio", models.TextField(help_text="Short bio about the mentor")),
                (
                    "picture",
                    models.URLField(
                        blank=True, help_text="URL to mentor's photo", null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ARTS", "Arts & Social Sciences"),
                            ("SCIENCE", "Science & Technology"),
                            ("RELIGIOUS", "Religious & Self Development"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is mentor currently accepting requests?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mentor",
                "verbose_name_plural": "Mentors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MentorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="User's message to the mentor", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONTACTED", "Contacted"),
                            ("MATCHED", "Matched"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="web.mentor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor Request",
                "verbose_name_plural": "Mentor Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
