# Generated by Django 5.2.8 on 2025-12-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_mentor_mentorrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Display label for the category", max_length=100
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("users", "Users (👥)"),
                            ("palette", "Palette (🎨)"),
                            ("flask", "Flask (🧪)"),
                            ("heart", "Heart (❤️)"),
                            ("book", "Book (📚)"),
                            ("briefcase", "Briefcase (💼)"),
                            ("music", "Music (🎵)"),
                            ("globe", "Globe (🌍)"),
                            ("code", "Code (💻)"),
                            ("graduation", "Graduation (🎓)"),
                            ("star", "Star (⭐)"),
                            ("lightbulb", "Lightbulb (💡)"),
                        ],
                        default="users",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which categories appear"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Mentor Category",
                "verbose_name_plural": "Mentor Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="mentor",
            name="language",
            field=models.CharField(
                choices=[("EN", "English"), ("FR", "French"), ("BI", "Bilingual")],
                default="BI",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentors",
                to="web.mentorcategory",
            ),
        ),
    ]
