# Generated by Django 5.2.8 on 2025-12-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0014_mentorcategory_mentor_language_alter_mentor_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="picture_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload mentor's photo directly",
                null=True,
                upload_to="mentors/",
            ),
        ),
        migrations.AddField(
            model_name="mentorrequest",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this mentorship connection expires",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="picture",
            field=models.URLField(
                blank=True,
                help_text="URL to mentor's photo (if no file uploaded)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mentorrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONTACTED", "Contacted"),
                    ("MATCHED", "Matched"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
